version: '3.8'
services:
  # 1. Database (PostgreSQL + GIS)
  db:
    image: postgis/postgis:15-3.3 # Image hỗ trợ GeoLocation
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: food_delivery
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # 2. Caching & Queue Broker
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 3. UI quản lý DB (Optional nhưng nên có)

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db  # Tự điền sẵn host là "db" cho đỡ phải gõ
    volumes:
      # Ánh xạ file css ở máy thật vào đúng chỗ Adminer cần trong container
      - ./adminer.css:/var/www/html/adminer.css
volumes:
  pg_data:
